<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE us-patent-assignments [<!ELEMENT us-patent-assignments (action-key-code, transaction-date, patent-assignments)>
<!ATTLIST us-patent-assignments  dtd-version   CDATA  #IMPLIED
                                 date-produced CDATA  #IMPLIED>
<!ELEMENT action-key-code (#PCDATA)>
<!ELEMENT transaction-date (date)>
<!ELEMENT patent-assignments (data-available-code | patent-assignment+)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT data-available-code (#PCDATA)>
<!ELEMENT patent-assignment (assignment-record, patent-assignors, patent-assignees, patent-properties)>
<!ELEMENT assignment-record (reel-no, frame-no, last-update-date, purge-indicator, recorded-date, page-count?, correspondent, conveyance-text)>
<!ELEMENT patent-assignors (patent-assignor+)>
<!ELEMENT patent-assignees (patent-assignee+)>
<!ELEMENT patent-properties (patent-property+)>
<!ELEMENT reel-no (#PCDATA)>
<!ELEMENT frame-no (#PCDATA)>
<!ELEMENT last-update-date (date)>
<!ELEMENT purge-indicator (#PCDATA)>
<!ELEMENT recorded-date (date)>
<!ELEMENT page-count (#PCDATA)>
<!ELEMENT correspondent (name, address-1?, address-2?, address-3?, address-4?)>
<!ELEMENT conveyance-text (#PCDATA)>
<!ELEMENT patent-assignor (name, execution-date?, date-acknowledged?)>
<!ELEMENT patent-assignee (name, address-1?, address-2?, city?, state?, country-name?, postcode?)>
<!ELEMENT patent-property (document-id*, invention-title?)>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name name-type (natural | legal)  #IMPLIED>
<!ELEMENT address-1 (#PCDATA)>
<!ELEMENT address-2 (#PCDATA)>
<!ELEMENT address-3 (#PCDATA)>
<!ELEMENT address-4 (#PCDATA)>
<!ELEMENT execution-date (date)>
<!ELEMENT date-acknowledged (date)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT country-name (#PCDATA)>
<!ELEMENT postcode (#PCDATA)>
<!ELEMENT document-id (country, doc-number, kind?, name?, date?)>
<!ELEMENT invention-title (#PCDATA | b | i | u | sup | sub)*>
<!ATTLIST invention-title  id   ID     #IMPLIED
                           lang CDATA  #REQUIRED>
<!ELEMENT country (#PCDATA)>
<!ELEMENT doc-number (#PCDATA)>
<!ELEMENT kind (#PCDATA)>
<!--bold formatting for text-->
<!ELEMENT b (#PCDATA | i | u | smallcaps)*>
<!--italic formatting for text-->
<!ELEMENT i (#PCDATA | b | u | smallcaps)*>
<!--underscore: style - single is default-->
<!ELEMENT u (#PCDATA | b | i | smallcaps)*>
<!ATTLIST u  style  (single | double | dash | dots )  'single' >
<!--superscripted text-->
<!ELEMENT sup (#PCDATA | b | u | i)*>
<!--subscripted text-->
<!ELEMENT sub (#PCDATA | b | u | i)*>
<!--small capitals-->
<!ELEMENT smallcaps (#PCDATA | b | u | i)*>
]>
<us-patent-assignments dtd-version="1.0" date-produced="20131101">
  <action-key-code>DA</action-key-code>
  <transaction-date>
    <date>20160101</date>
  </transaction-date>
  <patent-assignments>
    <patent-assignment>
      <assignment-record>
        <reel-no>37388</reel-no>
        <frame-no>92</frame-no>
        <last-update-date>
          <date>20160101</date>
        </last-update-date>
        <purge-indicator>N</purge-indicator>
        <recorded-date>
          <date>20151230</date>
        </recorded-date>
        <page-count>3</page-count>
        <correspondent>
          <name>CHRISTIE, PARKER &amp; HALE, LLP</name>
          <address-1>PO BOX 29001</address-1>
          <address-2>GLENDALE, CA 91209</address-2>
        </correspondent>
        <conveyance-text>ASSIGNMENT OF ASSIGNORS INTEREST (SEE DOCUMENT FOR DETAILS).</conveyance-text>
      </assignment-record>
      <patent-assignors>
        <patent-assignor>
          <name>WEINSTEIN, DAMON</name>
          <execution-date>
            <date>20060330</date>
          </execution-date>
        </patent-assignor>
        <patent-assignor>
          <name>SEGALL, TIMOTHY R.</name>
          <execution-date>
            <date>20060329</date>
          </execution-date>
        </patent-assignor>
        <patent-assignor>
          <name>LAIOSA, VINCENT E.</name>
          <execution-date>
            <date>20060329</date>
          </execution-date>
        </patent-assignor>
      </patent-assignors>
      <patent-assignees>
        <patent-assignee>
          <name>SOUNDBITE COMMUNICATIONS, INC.</name>
          <address-1>2 BURLINGTON WOODS DRIVE</address-1>
          <city>BURLINGTON</city>
          <state>MASSACHUSETTS</state>
          <postcode>01803</postcode>
        </patent-assignee>
      </patent-assignees>
      <patent-properties>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>14678893</doc-number>
            <kind>X0</kind>
            <date>20150403</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20150215460</doc-number>
            <kind>A1</kind>
            <date>20150730</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>9219817</doc-number>
            <kind>B2</kind>
            <date>20151222</date>
          </document-id>
          <invention-title lang="en">Method and System for Managing Interactive Communications Campaigns</invention-title>
        </patent-property>
      </patent-properties>
    </patent-assignment>
    <patent-assignment>
      <assignment-record>
        <reel-no>37388</reel-no>
        <frame-no>106</frame-no>
        <last-update-date>
          <date>20160101</date>
        </last-update-date>
        <purge-indicator>N</purge-indicator>
        <recorded-date>
          <date>20151230</date>
        </recorded-date>
        <page-count>5</page-count>
        <correspondent>
          <name>JAMES E. ARMSTRONG, IV</name>
          <address-1>P.O. BOX 55874</address-1>
          <address-2>BOSTON, MA 02205</address-2>
        </correspondent>
        <conveyance-text>ASSIGNMENT OF ASSIGNORS INTEREST (SEE DOCUMENT FOR DETAILS).</conveyance-text>
      </assignment-record>
      <patent-assignors>
        <patent-assignor>
          <name>OZAKI, NORIO</name>
          <execution-date>
            <date>20150318</date>
          </execution-date>
        </patent-assignor>
        <patent-assignor>
          <name>NAGAI, TAKU</name>
          <execution-date>
            <date>20150323</date>
          </execution-date>
        </patent-assignor>
        <patent-assignor>
          <name>YOSHIMI, AKIRA</name>
          <execution-date>
            <date>20150319</date>
          </execution-date>
        </patent-assignor>
        <patent-assignor>
          <name>YAMADA, SHINNOSUKE</name>
          <execution-date>
            <date>20150402</date>
          </execution-date>
        </patent-assignor>
        <patent-assignor>
          <name>HIRAKAWA, AKIHIRO</name>
          <execution-date>
            <date>20150323</date>
          </execution-date>
        </patent-assignor>
        <patent-assignor>
          <name>KUNIMOTO, SHOHKO</name>
          <execution-date>
            <date>20150326</date>
          </execution-date>
        </patent-assignor>
        <patent-assignor>
          <name>MATSUMOTO, YURIE</name>
          <execution-date>
            <date>20150412</date>
          </execution-date>
        </patent-assignor>
      </patent-assignors>
      <patent-assignees>
        <patent-assignee>
          <name>NATIONAL UNIVERSITY CORPORATION NAGOYA UNIVERSITY</name>
          <address-1>1, FURO-CHO, CHIKUSA-KU, AICHI</address-1>
          <city>NAGOYA-SHI</city>
          <country-name>JAPAN</country-name>
          <postcode>4648601</postcode>
        </patent-assignee>
      </patent-assignees>
      <patent-properties>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>14434207</doc-number>
            <kind>X0</kind>
            <date>20150408</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20150260729</doc-number>
            <kind>A1</kind>
            <date>20150917</date>
          </document-id>
          <invention-title lang="en">SCHIZOPHRENIA MARKER SET AND ITS UTILIZATION</invention-title>
        </patent-property>
      </patent-properties>
    </patent-assignment>
    <patent-assignment>
      <assignment-record>
        <reel-no>37388</reel-no>
        <frame-no>128</frame-no>
        <last-update-date>
          <date>20160101</date>
        </last-update-date>
        <purge-indicator>N</purge-indicator>
        <recorded-date>
          <date>20151230</date>
        </recorded-date>
        <page-count>5</page-count>
        <correspondent>
          <name>JAMES E. ARMSTRONG, IV</name>
          <address-1>P.O. BOX 55874</address-1>
          <address-2>BOSTON, MA 02205</address-2>
        </correspondent>
        <conveyance-text>ASSIGNMENT OF ASSIGNORS INTEREST (SEE DOCUMENT FOR DETAILS).</conveyance-text>
      </assignment-record>
      <patent-assignors>
        <patent-assignor>
          <name>UCHIDA, NAONARI</name>
          <execution-date>
            <date>20150428</date>
          </execution-date>
        </patent-assignor>
      </patent-assignors>
      <patent-assignees>
        <patent-assignee>
          <name>YAZAKI CORPORATION</name>
          <address-1>4-28, MITA 1-CHOME, MINATO-KU</address-1>
          <city>TOKYO</city>
          <country-name>JAPAN</country-name>
          <postcode>108-8333</postcode>
        </patent-assignee>
      </patent-assignees>
      <patent-properties>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>14696669</doc-number>
            <kind>X0</kind>
            <date>20150427</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20150229037</doc-number>
            <kind>A1</kind>
            <date>20150813</date>
          </document-id>
          <invention-title lang="en">TERMINAL-EQUIPPED WIRE AND METHOD FOR MANUFACTURING THE SAME</invention-title>
        </patent-property>
      </patent-properties>
    </patent-assignment>
    <patent-assignment>
      <assignment-record>
        <reel-no>37388</reel-no>
        <frame-no>136</frame-no>
        <last-update-date>
          <date>20160101</date>
        </last-update-date>
        <purge-indicator>N</purge-indicator>
        <recorded-date>
          <date>20151230</date>
        </recorded-date>
        <page-count>4</page-count>
        <correspondent>
          <name>JAMES E. ARMSTRONG, IV</name>
          <address-1>P.O. BOX 55874</address-1>
          <address-2>BOSTON, MA 02205</address-2>
        </correspondent>
        <conveyance-text>ASSIGNMENT OF ASSIGNORS INTEREST (SEE DOCUMENT FOR DETAILS).</conveyance-text>
      </assignment-record>
      <patent-assignors>
        <patent-assignor>
          <name>SEKINO, TSUKASA</name>
          <execution-date>
            <date>20150813</date>
          </execution-date>
        </patent-assignor>
        <patent-assignor>
          <name>KATO, SINJI</name>
          <execution-date>
            <date>20150813</date>
          </execution-date>
        </patent-assignor>
      </patent-assignors>
      <patent-assignees>
        <patent-assignee>
          <name>YAZAKI CORPORATION</name>
          <address-1>4-28, MITA 1-CHOME, MINATO-KU</address-1>
          <city>TOKYO</city>
          <country-name>JAPAN</country-name>
          <postcode>108-8333</postcode>
        </patent-assignee>
      </patent-assignees>
      <patent-properties>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>14762238</doc-number>
            <kind>X0</kind>
            <date>20150721</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20150360629</doc-number>
            <kind>A1</kind>
            <date>20151217</date>
          </document-id>
          <invention-title lang="en">REINFORCEMENT STRUCTURE FOR POWER-SUPPLYING CASE</invention-title>
        </patent-property>
      </patent-properties>
    </patent-assignment>
    <patent-assignment>
      <assignment-record>
        <reel-no>37388</reel-no>
        <frame-no>144</frame-no>
        <last-update-date>
          <date>20160101</date>
        </last-update-date>
        <purge-indicator>N</purge-indicator>
        <recorded-date>
          <date>20151230</date>
        </recorded-date>
        <page-count>5</page-count>
        <correspondent>
          <name>JAMES E. ARMSTRONG, IV</name>
          <address-1>P.O. BOX 55874</address-1>
          <address-2>BOSTON, MA 02205</address-2>
        </correspondent>
        <conveyance-text>ASSIGNMENT OF ASSIGNORS INTEREST (SEE DOCUMENT FOR DETAILS).</conveyance-text>
      </assignment-record>
      <patent-assignors>
        <patent-assignor>
          <name>KAWAMURA, KAZUSHIGE</name>
          <execution-date>
            <date>20150622</date>
          </execution-date>
        </patent-assignor>
        <patent-assignor>
          <name>TAKEDA, DAI</name>
          <execution-date>
            <date>20150622</date>
          </execution-date>
        </patent-assignor>
        <patent-assignor>
          <name>AWAI, EIJI</name>
          <execution-date>
            <date>20150622</date>
          </execution-date>
        </patent-assignor>
        <patent-assignor>
          <name>TAKEI, NOBORU</name>
          <execution-date>
            <date>20150619</date>
          </execution-date>
        </patent-assignor>
        <patent-assignor>
          <name>UEMURA, MASATAKA</name>
          <execution-date>
            <date>20150623</date>
          </execution-date>
        </patent-assignor>
      </patent-assignors>
      <patent-assignees>
        <patent-assignee>
          <name>CHIYODA CORPORATION</name>
          <address-1>4-6-2, MINATOMIRAI, NISHI-KU</address-1>
          <address-2>KANAGAWA</address-2>
          <city>YOKOHAMA-SHI</city>
          <country-name>JAPAN</country-name>
          <postcode>2208765</postcode>
        </patent-assignee>
      </patent-assignees>
      <patent-properties>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>14646858</doc-number>
            <kind>X0</kind>
            <date>20150522</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20150298056</doc-number>
            <kind>A1</kind>
            <date>20151022</date>
          </document-id>
          <invention-title lang="en">DESULFURIZATION METHOD AND DEVICE FOR SULFURIC ACID PRODUCTION DEVICE</invention-title>
        </patent-property>
      </patent-properties>
    </patent-assignment>
    <patent-assignment>
      <assignment-record>
        <reel-no>37388</reel-no>
        <frame-no>161</frame-no>
        <last-update-date>
          <date>20160101</date>
        </last-update-date>
        <purge-indicator>N</purge-indicator>
        <recorded-date>
          <date>20151230</date>
        </recorded-date>
        <page-count>5</page-count>
        <correspondent>
          <name>JAMES E. ARMSTRONG, IV</name>
          <address-1>P.O. BOX 55874</address-1>
          <address-2>BOSTON, MA 02205</address-2>
        </correspondent>
        <conveyance-text>ASSIGNMENT OF ASSIGNORS INTEREST (SEE DOCUMENT FOR DETAILS).</conveyance-text>
      </assignment-record>
      <patent-assignors>
        <patent-assignor>
          <name>NOMURA, AZUMI</name>
          <execution-date>
            <date>20150331</date>
          </execution-date>
        </patent-assignor>
        <patent-assignor>
          <name>YAMAMURA, MASAO</name>
          <execution-date>
            <date>20150331</date>
          </execution-date>
        </patent-assignor>
      </patent-assignors>
      <patent-assignees>
        <patent-assignee>
          <name>KOMATSU LTD.</name>
          <address-1>2-3-6, AKASAKA,MINATO-KU</address-1>
          <city>TOKYO</city>
          <country-name>JAPAN</country-name>
          <postcode>107-8414</postcode>
        </patent-assignee>
      </patent-assignees>
      <patent-properties>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>14429125</doc-number>
            <kind>X0</kind>
            <date>20150318</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20150218781</doc-number>
            <kind>A1</kind>
            <date>20150806</date>
          </document-id>
          <invention-title lang="en">DISPLAY SYSTEM OF EXCAVATING MACHINE AND EXCAVATING MACHINE</invention-title>
        </patent-property>
      </patent-properties>
    </patent-assignment>
    <patent-assignment>
      <assignment-record>
        <reel-no>37388</reel-no>
        <frame-no>169</frame-no>
        <last-update-date>
          <date>20160101</date>
        </last-update-date>
        <purge-indicator>N</purge-indicator>
        <recorded-date>
          <date>20151230</date>
        </recorded-date>
        <page-count>4</page-count>
        <correspondent>
          <name>JAMES E. ARMSTRONG, IV</name>
          <address-1>P.O. BOX 55874</address-1>
          <address-2>BOSTON, MA 02205</address-2>
        </correspondent>
        <conveyance-text>ASSIGNMENT OF ASSIGNORS INTEREST (SEE DOCUMENT FOR DETAILS).</conveyance-text>
      </assignment-record>
      <patent-assignors>
        <patent-assignor>
          <name>MINAKI, MASASHI</name>
          <execution-date>
            <date>20150331</date>
          </execution-date>
        </patent-assignor>
        <patent-assignor>
          <name>IZUMI, TSUYOSHI</name>
          <execution-date>
            <date>20150331</date>
          </execution-date>
        </patent-assignor>
        <patent-assignor>
          <name>OTA, YASUAKI</name>
          <execution-date>
            <date>20150331</date>
          </execution-date>
        </patent-assignor>
      </patent-assignors>
      <patent-assignees>
        <patent-assignee>
          <name>SANYO CHEMICAL INDUSTRIES, LTD</name>
          <address-1>11-1, IKKYO NOMOTOCHO, HIGASHIYAMA-KU</address-1>
          <address-2>KYOTO</address-2>
          <city>KYOTO-SHI</city>
          <country-name>JAPAN</country-name>
          <postcode>6050995</postcode>
        </patent-assignee>
      </patent-assignees>
      <patent-properties>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>14428741</doc-number>
            <kind>X0</kind>
            <date>20150317</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20150274914</doc-number>
            <kind>A1</kind>
            <date>20151001</date>
          </document-id>
          <invention-title lang="en">RESIN PARTICLES AND METHOD FOR PRODUCING SAME</invention-title>
        </patent-property>
      </patent-properties>
    </patent-assignment>
    <patent-assignment>
      <assignment-record>
        <reel-no>37388</reel-no>
        <frame-no>177</frame-no>
        <last-update-date>
          <date>20160101</date>
        </last-update-date>
        <purge-indicator>N</purge-indicator>
        <recorded-date>
          <date>20151230</date>
        </recorded-date>
        <page-count>4</page-count>
        <correspondent>
          <name>JAMES E. ARMSTRONG, IV</name>
          <address-1>P.O. BOX 55874</address-1>
          <address-2>BOSTON, MA 02205</address-2>
        </correspondent>
        <conveyance-text>ASSIGNMENT OF ASSIGNORS INTEREST (SEE DOCUMENT FOR DETAILS).</conveyance-text>
      </assignment-record>
      <patent-assignors>
        <patent-assignor>
          <name>UEDA, YUSUKE</name>
          <execution-date>
            <date>20150524</date>
          </execution-date>
        </patent-assignor>
      </patent-assignors>
      <patent-assignees>
        <patent-assignee>
          <name>SANYO CHEMICAL INDUSTRIES, LTD.</name>
          <address-1>11-1, IKKYO NOMOTOCHO, HIGASHIYAMA-KU</address-1>
          <address-2>KYOTO</address-2>
          <city>KYOTO-SHI</city>
          <country-name>JAPAN</country-name>
          <postcode>6050995</postcode>
        </patent-assignee>
      </patent-assignees>
      <patent-properties>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>14430037</doc-number>
            <kind>X0</kind>
            <date>20150320</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20150246992</doc-number>
            <kind>A1</kind>
            <date>20150903</date>
          </document-id>
          <invention-title lang="en">AQUEOUS LIQUID ABSORBING RESIN, AQUEOUS LIQUID ABSORBING COMPOSITION, AND ABSORBENT BODY AND ABSORBENT ARTICLE USING SAME</invention-title>
        </patent-property>
      </patent-properties>
    </patent-assignment>
    <patent-assignment>
      <assignment-record>
        <reel-no>37388</reel-no>
        <frame-no>184</frame-no>
        <last-update-date>
          <date>20160101</date>
        </last-update-date>
        <purge-indicator>N</purge-indicator>
        <recorded-date>
          <date>20151230</date>
        </recorded-date>
        <page-count>4</page-count>
        <correspondent>
          <name>JAMES E. ARMSTRONG, IV</name>
          <address-1>P.O. BOX 55874</address-1>
          <address-2>BOSTON, MA 02205</address-2>
        </correspondent>
        <conveyance-text>ASSIGNMENT OF ASSIGNORS INTEREST (SEE DOCUMENT FOR DETAILS).</conveyance-text>
      </assignment-record>
      <patent-assignors>
        <patent-assignor>
          <name>I, SUNSOKU</name>
          <execution-date>
            <date>20140620</date>
          </execution-date>
        </patent-assignor>
        <patent-assignor>
          <name>KAKIMI, TAKAAKI</name>
          <execution-date>
            <date>20140620</date>
          </execution-date>
        </patent-assignor>
      </patent-assignors>
      <patent-assignees>
        <patent-assignee>
          <name>YAZAKI CORPORATION</name>
          <address-1>4-28, MITA 1-CHOME, MINATO-KU</address-1>
          <city>TOKYO</city>
          <country-name>JAPAN</country-name>
          <postcode>108-8333</postcode>
        </patent-assignee>
      </patent-assignees>
      <patent-properties>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>14194850</doc-number>
            <kind>X0</kind>
            <date>20140303</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20140246217</doc-number>
            <kind>A1</kind>
            <date>20140904</date>
          </document-id>
          <invention-title lang="en">ELECTRICAL JUNCTION BOX</invention-title>
        </patent-property>
      </patent-properties>
    </patent-assignment>
    <patent-assignment>
      <assignment-record>
        <reel-no>37388</reel-no>
        <frame-no>211</frame-no>
        <last-update-date>
          <date>20160101</date>
        </last-update-date>
        <purge-indicator>N</purge-indicator>
        <recorded-date>
          <date>20151230</date>
        </recorded-date>
        <page-count>4</page-count>
        <correspondent>
          <name>JAMES E. ARMSTRONG, IV</name>
          <address-1>P.O. BOX 55874</address-1>
          <address-2>BOSTON, MA 02205</address-2>
        </correspondent>
        <conveyance-text>ASSIGNMENT OF ASSIGNORS INTEREST (SEE DOCUMENT FOR DETAILS).</conveyance-text>
      </assignment-record>
      <patent-assignors>
        <patent-assignor>
          <name>I, SUNSOKU</name>
          <execution-date>
            <date>20140620</date>
          </execution-date>
        </patent-assignor>
        <patent-assignor>
          <name>KAKIMI, TAKAAKI</name>
          <execution-date>
            <date>20140620</date>
          </execution-date>
        </patent-assignor>
      </patent-assignors>
      <patent-assignees>
        <patent-assignee>
          <name>YAZAKI CORPORATION</name>
          <address-1>4-28, MITA 1-CHOME, MINATO-KU</address-1>
          <city>TOKYO</city>
          <country-name>JAPAN</country-name>
          <postcode>108-8333</postcode>
        </patent-assignee>
      </patent-assignees>
      <patent-properties>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>14267163</doc-number>
            <kind>X0</kind>
            <date>20140501</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20140335744</doc-number>
            <kind>A1</kind>
            <date>20141113</date>
          </document-id>
          <invention-title lang="en">ROUND TERMINAL FIXATION STRUCTURE</invention-title>
        </patent-property>
      </patent-properties>
    </patent-assignment>
    <patent-assignment>
      <assignment-record>
        <reel-no>37388</reel-no>
        <frame-no>230</frame-no>
        <last-update-date>
          <date>20160101</date>
        </last-update-date>
        <purge-indicator>N</purge-indicator>
        <recorded-date>
          <date>20151230</date>
        </recorded-date>
        <page-count>4</page-count>
        <correspondent>
          <name>JAMES E. ARMSTRONG, IV</name>
          <address-1>P.O. BOX 55874</address-1>
          <address-2>BOSTON, MA 02205</address-2>
        </correspondent>
        <conveyance-text>ASSIGNMENT OF ASSIGNORS INTEREST (SEE DOCUMENT FOR DETAILS).</conveyance-text>
      </assignment-record>
      <patent-assignors>
        <patent-assignor>
          <name>IMADA, TOMOYUKI</name>
          <execution-date>
            <date>20150109</date>
          </execution-date>
        </patent-assignor>
        <patent-assignor>
          <name>KAGE, TAKAKAZU</name>
          <execution-date>
            <date>20150113</date>
          </execution-date>
        </patent-assignor>
        <patent-assignor>
          <name>SHIN, DONGMI</name>
          <execution-date>
            <date>20130113</date>
          </execution-date>
        </patent-assignor>
      </patent-assignors>
      <patent-assignees>
        <patent-assignee>
          <name>DIC CORPORATION</name>
          <address-1>35-58, SAKASHITA 3-CHOME, ITABASHI-KU</address-1>
          <city>TOKYO</city>
          <country-name>JAPAN</country-name>
          <postcode>174-8520</postcode>
        </patent-assignee>
      </patent-assignees>
      <patent-properties>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>14415337</doc-number>
            <kind>X0</kind>
            <date>20150116</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20150166459</doc-number>
            <kind>A1</kind>
            <date>20150618</date>
          </document-id>
          <invention-title lang="en">RADICALLY CURABLE COMPOUND, METHOD FOR PRODUCING RADICALLY CURABLE COMPOUND, RADICALLY CURABLE COMPOSITION, CURED PRODUCT OF THE SAME, AND RESIST-MATERIAL COMPOSITION</invention-title>
        </patent-property>
      </patent-properties>
    </patent-assignment>
    <patent-assignment>
      <assignment-record>
        <reel-no>37388</reel-no>
        <frame-no>248</frame-no>
        <last-update-date>
          <date>20160101</date>
        </last-update-date>
        <purge-indicator>N</purge-indicator>
        <recorded-date>
          <date>20151230</date>
        </recorded-date>
        <page-count>10</page-count>
        <correspondent>
          <name>JAMES E. ARMSTRONG, IV</name>
          <address-1>P.O. BOX 55874</address-1>
          <address-2>BOSTON, MA 02205</address-2>
        </correspondent>
        <conveyance-text>ASSIGNMENT OF ASSIGNORS INTEREST (SEE DOCUMENT FOR DETAILS).</conveyance-text>
      </assignment-record>
      <patent-assignors>
        <patent-assignor>
          <name>OGUMA, NOBUHIRO</name>
          <execution-date>
            <date>20150625</date>
          </execution-date>
        </patent-assignor>
        <patent-assignor>
          <name>HIROSE, SHIMPEI</name>
          <execution-date>
            <date>20150625</date>
          </execution-date>
        </patent-assignor>
        <patent-assignor>
          <name>SYOJI, KAZUYA</name>
          <execution-date>
            <date>20150625</date>
          </execution-date>
        </patent-assignor>
        <patent-assignor>
          <name>NAKAMURA, MASATOSHI</name>
          <execution-date>
            <date>20150625</date>
          </execution-date>
        </patent-assignor>
        <patent-assignor>
          <name>YASUDA, YASUO</name>
          <execution-date>
            <date>20150625</date>
          </execution-date>
        </patent-assignor>